apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: nocodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nocodb
    app.kubernetes.io/version: 0.263.1
    helm.sh/chart: nocodb-0.66.0
  name: nocodb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: nocodb
    app.kubernetes.io/name: nocodb
  type: LoadBalancer
